from bot.routers.menu.menu import menu_router
from bot.routers.menu.priority import priority_router
from bot.routers.menu.help import help_router
from bot.routers.menu.donate import donate_router
from bot.routers.menu.joke import joke_router
from bot.routers.schedule.schedule import schedule_router
from bot.routers.schedule.edit import edit_router
from bot.routers.schedule.edit_personal import edit_personal_router
from bot.routers.schedule.edit_headman import edit_headman_router
from bot.routers.schedule.blueprints import blueprints_router
