from botrayado.routers.menu import menu_router
from botrayado.routers.schedule import schedule_router
from botrayado.routers.joke import joke_router
from botrayado.routers.donate import donate_router
from botrayado.routers.help import help_router
from botrayado.routers.aliases import aliases_router
from botrayado.routers.config import config_router
from botrayado.routers.admin import admin_router
from botrayado.routers.edit import edit_router
from botrayado.routers.lookheadman import lookheadman_router
from botrayado.routers.idiots import idiots_router
