from bot.schedule.schedule import get_schedule_for_day
from bot.schedule.schedule import get_schedule_for_whole_week
from bot.schedule.schedule import get_schedule_custom_headman
from bot.schedule.schedule import get_schedule_custom_personal
