from routers.menu import menu_router
from routers.schedule import schedule_router
from routers.joke import joke_router
from routers.easter_egg import easter_egg_router
from routers.rickroll import geobot_router
from routers.help import help_router
from routers.aliases import aliases_router
from routers.idiots import idiots_router
from routers.config import config_router
